### ISSUE TITLE
About CRUD

### ISSUE THREAD

**Issue by OfranSassi** [GaurangShukla/College-ERP#3]
Hello, first of all, I want to thank you for providing us with the source code of this project, and second I need some help with something, the project runs perfectly on my local machine but when it comes to adding courses, students, teachers, or exams I can't add anything, nothing goes through, I hope you can tell me how to fix that!

Thank you :)

**Comment by GaurangShukla** [comment]
Hi @OfranSassi please install mongodb on your local machine and connect it locally with the code. Goto server/classes/Database_Test_db.js and change the mongo db uri to "mongodb://127.0.0.1:27017" on line 45, then start client and server. You can see all the changes in the local mongodb gui. If you want to go online please make an account on mongodb and add your own uri to the code, this process is a bit long and time consuming rather than the offline one. Thanks and please come back if need anything else.

**Comment by OfranSassi** [comment]
It worked flawlessly thank you so much!! 😍😍

**Comment by GaurangShukla** [comment]
> It worked flawlessly thank you so much!! 😍😍

Glad to be of help.

**Comment by OfranSassi** [comment]
*Hey sorry for bothering again, I wanted to ask you something, I'm trying
to replace the title "test" on the navbar of the site with another title
but it doesn't seem to work, do you have any idea why? I tried to modify it
in the Navbar.js and index.html file but I still get "test" as a title. *
